### ISSUE TITLE
update tutorial to reflect environment class updates

### ISSUE THREAD

**Issue by satra** [nipype/pydra-tutorial#53]
@djarecka - is this still valid? https://nipype.github.io/pydra-tutorial/notebooks/5_intro_shelltask.html#dockertask

**Comment by bclenet** [comment]
Hi, section *5.4. DockerTask* of the tutorial does not work with pydra 0.23, as it raises the following error : 
```AttributeError: module 'pydra' has no attribute 'DockerTask'```

Still with pydra 0.23, section *5.4.1.1. Using ShellCommandTask with container_info argument* would not work as expected either. The two pieces of code (with or without `container_info`) return the same result.

**Comment by djarecka** [comment]
@bclenet - thank you for pointing to this.
